
CREATE TABLE EMPLOYEFORLAB2(
EmpNo INT PRIMARY KEY,
EmpName VARCHAR(50) NOT NULL,
Gender CHAR(1) NOT NULL CHECK (Gender ="M" or Gender="F"),
Salary INT NOT NULL,
Address VARCHAR(50) NOT NULL,
DNo INT NOT NULL
);
DROP TABLE EMPLOYEFORLAB2;
CREATE TABLE DEPARTMENTFORLAB2(
Deptno INT PRIMARY KEY,
Deptname VARCHAR(50) UNIQUE
);
DROP TABLE DEPARTMENTFORLAB2;
ALTER TABLE EMPLOYEFORLAB2 ADD CONSTRAINT DNo
FOREIGN KEY(DNo) REFERENCES DEPARTMENTFORLAB2(Deptno)
ON DELETE CASCADE
ON UPDATE CASCADE;

INSERT INTO EMPLOYEFORLAB2(EmpNo,EmpName,Gender,Salary,Address,DNo)
VALUES
(1,"Ayan","M",20000,"Mumbai",101),
(2,"Divej","M",50000,"Gurgaon",102),
(3,"Ayanika","F",40000,"Assam",103);

INSERT INTO DEPARTMENTFORLAB2(Deptno,Deptname)
VALUES
(101,"Chemical"),
(102,"Information Technology"),
(103,"Computer Science"),
(104,"Automobile");

SELECT * FROM EMPLOYEFORLAB2;
SELECT * FROM DEPARTMENTFORLAB2;

INSERT INTO EMPLOYEFORLAB2(EmpNo,EmpName,Gender,Salary,Address,DNo)
VALUES
(9,NULL,"M",20000,"Mumbai",101),
(4,"Divej","M",NULL,"Gurgaon",102),
(8,"Ayanika","F",40000,"Assam",103);

ALTER TABLE EMPLOYEFORLAB2
MODIFY salary INT DEFAULT 25000;

INSERT INTO EMPLOYEFORLAB2(EmpNo,EmpName,Gender,Address,DNo)
VALUES
(4,"Arjun","M","Mumbai",101),
(5,"Sneha","F","Gurgaon",102),
(6,"Ayanika","F","Assam",103);

DELETE FROM DEPARTMENTFORLAB2
WHERE Deptno=101;



